# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csmap_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from qgis.PyQt import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_CSMapDialogBase(object):
    def setupUi(self, CSMapDialogBase):
        CSMapDialogBase.setObjectName(_fromUtf8("CSMapDialogBase"))
        CSMapDialogBase.resize(411, 405)
        self.button_box = QtWidgets.QDialogButtonBox(CSMapDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 370, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.demlayer_box = QgsMapLayerComboBox(CSMapDialogBase)
        self.demlayer_box.setGeometry(QtCore.QRect(140, 90, 251, 27))
        self.demlayer_box.setObjectName(_fromUtf8("demlayer_box"))
        self.demlayer_box.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.demlayer_label = QtWidgets.QLabel(CSMapDialogBase)
        self.demlayer_label.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.demlayer_label.setObjectName(_fromUtf8("demlayer_label"))
        self.curvature_box = QtWidgets.QComboBox(CSMapDialogBase)
        self.curvature_box.setGeometry(QtCore.QRect(140, 260, 251, 22))
        self.curvature_box.setObjectName(_fromUtf8("curvature_box"))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_box.addItem(_fromUtf8(""))
        self.curvature_label = QtWidgets.QLabel(CSMapDialogBase)
        self.curvature_label.setGeometry(QtCore.QRect(20, 260, 111, 31))
        self.curvature_label.setObjectName(_fromUtf8("curvature_label"))
        self.csmap_button = QtWidgets.QRadioButton(CSMapDialogBase)
        self.csmap_button.setGeometry(QtCore.QRect(30, 40, 86, 16))
        self.csmap_button.setChecked(True)
        self.csmap_button.setObjectName(_fromUtf8("csmap_button"))
        self.csmap_mode = QtWidgets.QButtonGroup(CSMapDialogBase)
        self.csmap_mode.setObjectName(_fromUtf8("csmap_mode"))
        self.csmap_mode.addButton(self.csmap_button)
        self.csmpa_button2 = QtWidgets.QRadioButton(CSMapDialogBase)
        self.csmpa_button2.setGeometry(QtCore.QRect(130, 40, 211, 16))
        self.csmpa_button2.setObjectName(_fromUtf8("csmpa_button2"))
        self.csmap_mode.addButton(self.csmpa_button2)
        self.groupBox = QtWidgets.QGroupBox(CSMapDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 371, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtWidgets.QLabel(CSMapDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 161, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.param_standard = QgsSpinBox(CSMapDialogBase)
        self.param_standard.setGeometry(QtCore.QRect(190, 170, 83, 27))
        self.param_standard.setProperty("value", 3)
        self.param_standard.setObjectName(_fromUtf8("param_standard"))
        self.label_4 = QtWidgets.QLabel(CSMapDialogBase)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 121, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtWidgets.QLabel(CSMapDialogBase)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 41, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.param_radius = QgsSpinBox(CSMapDialogBase)
        self.param_radius.setGeometry(QtCore.QRect(190, 210, 83, 27))
        self.param_radius.setProperty("value", 12)
        self.param_radius.setObjectName(_fromUtf8("param_radius"))
        self.load_flg = QtWidgets.QCheckBox(CSMapDialogBase)
        self.load_flg.setGeometry(QtCore.QRect(20, 350, 341, 16))
        self.load_flg.setObjectName(_fromUtf8("load_flg"))
        self.output_folder_select = QtWidgets.QToolButton(CSMapDialogBase)
        self.output_folder_select.setGeometry(QtCore.QRect(350, 320, 41, 21))
        self.output_folder_select.setObjectName(_fromUtf8("output_folder_select"))
        self.output_folder_edit = QtWidgets.QLineEdit(CSMapDialogBase)
        self.output_folder_edit.setEnabled(False)
        self.output_folder_edit.setGeometry(QtCore.QRect(140, 320, 201, 20))
        self.output_folder_edit.setAutoFillBackground(False)
        self.output_folder_edit.setObjectName(_fromUtf8("output_folder_edit"))
        self.output_folder_label = QtWidgets.QLabel(CSMapDialogBase)
        self.output_folder_label.setGeometry(QtCore.QRect(20, 320, 111, 31))
        self.output_folder_label.setObjectName(_fromUtf8("output_folder_label"))
        self.input_folder_label = QtWidgets.QLabel(CSMapDialogBase)
        self.input_folder_label.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.input_folder_label.setObjectName(_fromUtf8("input_folder_label"))
        self.input_folder_select = QtWidgets.QToolButton(CSMapDialogBase)
        self.input_folder_select.setGeometry(QtCore.QRect(350, 90, 41, 21))
        self.input_folder_select.setObjectName(_fromUtf8("input_folder_select"))
        self.input_folder_edit = QtWidgets.QLineEdit(CSMapDialogBase)
        self.input_folder_edit.setEnabled(False)
        self.input_folder_edit.setGeometry(QtCore.QRect(140, 90, 201, 20))
        self.input_folder_edit.setAutoFillBackground(False)
        self.input_folder_edit.setObjectName(_fromUtf8("input_folder_edit"))
        self.groupBox.raise_()
        self.button_box.raise_()
        self.demlayer_box.raise_()
        self.demlayer_label.raise_()
        self.curvature_box.raise_()
        self.curvature_label.raise_()
        self.csmap_button.raise_()
        self.csmpa_button2.raise_()
        self.label_3.raise_()
        self.param_standard.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.param_radius.raise_()
        self.load_flg.raise_()
        self.output_folder_select.raise_()
        self.output_folder_edit.raise_()
        self.output_folder_label.raise_()
        self.input_folder_label.raise_()
        self.input_folder_select.raise_()
        self.input_folder_edit.raise_()

        self.retranslateUi(CSMapDialogBase)
        self.button_box.accepted.connect(CSMapDialogBase.accept)
        self.button_box.rejected.connect(CSMapDialogBase.reject)
        self.csmpa_button2.pressed.connect(self.curvature_box.hide)
        self.csmap_button.pressed.connect(self.curvature_box.show)
        self.csmpa_button2.pressed.connect(self.curvature_label.hide)
        self.csmap_button.pressed.connect(self.curvature_label.show)
        self.output_folder_select.pressed.connect(CSMapDialogBase.output_folder_action)
        self.input_folder_select.pressed.connect(CSMapDialogBase.input_folder_action)
        QtCore.QMetaObject.connectSlotsByName(CSMapDialogBase)
        CSMapDialogBase.setTabOrder(self.csmap_button, self.csmpa_button2)
        CSMapDialogBase.setTabOrder(self.csmpa_button2, self.input_folder_edit)
        CSMapDialogBase.setTabOrder(self.input_folder_edit, self.input_folder_select)
        CSMapDialogBase.setTabOrder(self.input_folder_select, self.demlayer_box)
        CSMapDialogBase.setTabOrder(self.demlayer_box, self.param_standard)
        CSMapDialogBase.setTabOrder(self.param_standard, self.param_radius)
        CSMapDialogBase.setTabOrder(self.param_radius, self.curvature_box)
        CSMapDialogBase.setTabOrder(self.curvature_box, self.output_folder_edit)
        CSMapDialogBase.setTabOrder(self.output_folder_edit, self.output_folder_select)
        CSMapDialogBase.setTabOrder(self.output_folder_select, self.load_flg)
        CSMapDialogBase.setTabOrder(self.load_flg, self.button_box)

    def retranslateUi(self, CSMapDialogBase):
        CSMapDialogBase.setWindowTitle(_translate("CSMapDialogBase", "CSMapMaker", None))
        self.demlayer_label.setText(_translate("CSMapDialogBase", "DEM Layer", None))
        self.curvature_box.setItemText(0, _translate("CSMapDialogBase", "General Curvature", None))
        self.curvature_box.setItemText(1, _translate("CSMapDialogBase", "Profile Curvature", None))
        self.curvature_box.setItemText(2, _translate("CSMapDialogBase", "Plan Curvature", None))
        self.curvature_box.setItemText(3, _translate("CSMapDialogBase", "Tangential Curvature", None))
        self.curvature_box.setItemText(4, _translate("CSMapDialogBase", "Longitudinal Curvature", None))
        self.curvature_box.setItemText(5, _translate("CSMapDialogBase", "Cross-Sectional Curvature", None))
        self.curvature_box.setItemText(6, _translate("CSMapDialogBase", "Minimal Curvature", None))
        self.curvature_box.setItemText(7, _translate("CSMapDialogBase", "Maximal Curvature", None))
        self.curvature_box.setItemText(8, _translate("CSMapDialogBase", "Total Curvature", None))
        self.curvature_box.setItemText(9, _translate("CSMapDialogBase", "Flow Line Curvature", None))
        self.curvature_label.setText(_translate("CSMapDialogBase", "Curvature Method", None))
        self.csmap_button.setText(_translate("CSMapDialogBase", "CS-MAP", None))
        self.csmpa_button2.setText(_translate("CSMapDialogBase", "CS-MAP(Plan+General)", None))
        self.groupBox.setTitle(_translate("CSMapDialogBase", "mode", None))
        self.label_3.setText(_translate("CSMapDialogBase", "Gaussian Filter Parameters", None))
        self.label_4.setText(_translate("CSMapDialogBase", "Standard Deviation", None))
        self.label_5.setText(_translate("CSMapDialogBase", "Radius", None))
        self.load_flg.setText(_translate("CSMapDialogBase", "Open output file after running algorithm", None))
        self.output_folder_select.setText(_translate("CSMapDialogBase", "...", None))
        self.output_folder_label.setText(_translate("CSMapDialogBase", "Output Folder", None))
        self.input_folder_label.setText(_translate("CSMapDialogBase", "Input Folder", None))
        self.input_folder_select.setText(_translate("CSMapDialogBase", "...", None))

from qgis.gui import QgsMapLayerComboBox, QgsSpinBox
from qgis.core import QgsMapLayerProxyModel
